apiVersion: apps.openshift.io/v1alpha1
kind: ServiceBindingRequest
metadata:
  name: mytranslator.to.nodejs-app
  namespace: service-binding-demo
spec:
  backingServiceSelector:
    group: ibmcloud.ibm.com
    version: v1alpha1
    kind: Binding
    resourceRef: mytranslator-binding
  applicationSelector:
    matchLabels:
      app: language-translator-nodejs
    group: apps.openshift.io
    version: v1
    resource: deploymentconfigs
  customEnvVar:
     - name: LANGUAGE_TRANSLATOR_URL
       value: '{{ index .status.secretName "url" }}'
     - name: LANGUAGE_TRANSLATOR_IAM_APIKEY
       value: '{{ index .status.secretName "apikey" }}'    
